### ISSUE TITLE
Capability for images of suppliers to be sent from admin front end and stored in back end [Main Page]

### ISSUE THREAD

**Issue by evan01** [evan01/assetdesigns#73]

**Comment by jasondias9** [comment]
Supplier View - ability to remove attached image
<img width="776" alt="screen shot 2018-03-23 at 2 18 36 pm" src="https://user-images.githubusercontent.com/11682191/37846830-416eaea2-2ea5-11e8-8f8e-ed78db02ceb3.png">

Supplier Form - ability to add / edit supplier with attach image option
<img width="346" alt="screen shot 2018-03-23 at 2 20 15 pm" src="https://user-images.githubusercontent.com/11682191/37846856-596b9bd2-2ea5-11e8-9c72-8d58afdfb762.png">
