### ISSUE TITLE
Migrate Navigation bar Changes to Website

### ISSUE THREAD

**Issue by evan01** [evan01/assetdesigns#80]

**Comment by alliMD** [comment]
![screen shot 2018-03-21 at 6 30 42 pm](https://user-images.githubusercontent.com/25107052/37740998-20adae86-2d36-11e8-948a-278b3d3dd24d.png)
![screen shot 2018-03-21 at 6 30 57 pm](https://user-images.githubusercontent.com/25107052/37741002-246956f6-2d36-11e8-84f9-c75737b96b64.png)
Migrated the navigation bar effect and changed the settings for a hamburger navigation bar with a black transparent effect
