### ISSUE TITLE
Migrate Instagram app changes to website, Tessa just wants 3 pictures

### ISSUE THREAD

**Issue by evan01** [evan01/assetdesigns#82]

**Comment by jasondias9** [comment]
<img width="1377" alt="screen shot 2018-03-23 at 10 38 31 am" src="https://user-images.githubusercontent.com/11682191/37835371-646e8c02-2e86-11e8-9db5-40b389ac384c.png">

**Comment by jasondias9** [comment]
updated the text 
<img width="1278" alt="screen shot 2018-03-23 at 10 43 47 am" src="https://user-images.githubusercontent.com/11682191/37835689-1d1f7bb2-2e87-11e8-8400-fcae894e6d94.png">
