### ISSUE TITLE
Migrate Press page changes from sprint 1 to website

### ISSUE THREAD

**Issue by evan01** [evan01/assetdesigns#83]

**Comment by puranik9** [comment]
Migrated the Press Page changes to the website as shown in the screenshots. It now displays a grid layout with images and text for each press item as per the requirements.

<img width="731" alt="screen shot 2018-03-22 at 11 20 56 pm" src="https://user-images.githubusercontent.com/8695013/37809903-cc246eac-2e27-11e8-86ce-58be30cfa7ed.png">
<img width="695" alt="screen shot 2018-03-22 at 11 21 18 pm" src="https://user-images.githubusercontent.com/8695013/37809904-cc349700-2e27-11e8-8cfe-227bcfeb5b14.png">

**Comment by puranik9** [comment]
As per Tessa's requirement, I added some CSS to set image heights to be the same (and render proportional widths). I think everything looks good, can be reviewed and closed whenever.

Screenshots:

<img width="799" alt="screen shot 2018-03-23 at 10 10 39 pm" src="https://user-images.githubusercontent.com/8695013/37859331-417e5e72-2ee8-11e8-8d2b-ffa627c698c1.png">
<img width="827" alt="screen shot 2018-03-23 at 10 10 52 pm" src="https://user-images.githubusercontent.com/8695013/37859332-418dec0c-2ee8-11e8-9919-933282161459.png">
